"""Add users

Revision ID: 855444c0f125
Revises: de5dfcc23ce2
Create Date: 2024-12-10 20:41:10.317458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855444c0f125'
down_revision = 'de5dfcc23ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
